version: "3"

services:
  mc:
    image: itzg/minecraft-server:java17-jdk
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: "10G"
      TZ: "Asia/Hong_Kong"
      ONLINE_MODE: "FALSE"
      ALLOW_FLIGHT: "TRUE"
      MODE: "survival"
      SPAWN_PROTECTION: "0"
      ENABLE_COMMAND_BLOCK: "true"
      MAX_PLAYERS: "50"
      DIFFICULTY: hard
      MOTD: "&kxx&r Minecraft World &kxx&r"
      GENERIC_PACKS: https://mediafilez.forgecdn.net/files/4064/334/Create+Astral+Server+Pack+v1.2.zip
      TYPE: FABRIC
      VERSION: "1.18.2"
      SKIP_GENERIC_PACK_UPDATE_CHECK: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
      - ./mods:/mods